FORMAT: 1A

# ODS Events API

## Summary
The ODS API is designed to present the L.L.Bean Outdoor Discovery School 
activities, events and reservations.

### Example
The following example will illustrate how to obtain an ODS Event using curl 
commands. The purpose of this example is to provide working code for 
accomplishing the requirements of your app.

This guide presents a step by step process to help you gain immediate access 
to the ODS Events API so you may look around right away. Please do take copious 
notes of these commands as it's best to have a firm understanding of the most 
basic requests.

The following example makes a fictitious request using the consumer app key.

~~~
curl  https://api.llbean.com/v1/events/83669  -H "key: YWFiYmNjZGRlZTEyMzQ1OjIyMjMzNDQ1NQ
~~~

> But I'm getting a "HTTP/1.1 401 API is secure. Needs security Credentials" error!

If you've already asked yourself this question, or have seen one of these 
errors; you may have moved too fast. Please review the developer channel 
Getting Started Guide here.

If you have difficulties with any of these please email the API management 
team api@llbean.com or start a conversation in the forum.

The following example provides the most basic Events API response payload.

~~~
Example response goes here
~~~

Congratulations! You're Done!

> Are you serious? Is that all? Okay, you must be kidding me?

There's a lot more. However, before digging in much deeper it is important 
to note that the L.L.Bean Public Event represents a very complex data model. With 
this understanding, and to aid in the usability of the API, our team focuses 
on the minimum viable product you, the developer, may require to build your fantastic app.

## Entity Expansion 

Remove this section of entity expansion does not apply for this API

Many of the L.L.Bean APIs support what we like to call entity expansion 
or "expands parameters". These querystring parameters allow the app developer 
to choose what portions of the entity are appropriate for the use case.

In addition, these options allow our API product owners to decide which 
entities make sense to allow developers to access.


## Security
First and foremost is security. On our API Platform the consumer app is a 
trusted system that interacts with L.L.Bean digital assets via an API. The 
L.L.Bean Events API is protected with three factors:

### 1. Consumer Key Validation

It is important to protect L.L.Bean APIs from unauthorized access. One of 
the primary ways we do this is by validating your API consumer application key.

All developer apps must be approved by an L.L.Bean API administrator and 
will be provided a consumer key and secret. It is of utmost importance 
that you, the app developer, treat these credentials with special care.

When making requests to L.L.Bean Events API you will be required to provide your Consumer key.

> Your consumer app key is unique for your app and should be kept in a secure location.

* Do NOT store consumer keys in your source management system.
* Do NOT reference your key in your application documents.
* Do NOT allow your key to be exposed in .bash_history files.
* Do NOT post your key on the developers forum or when sending emails into the API Team.
* Do NOT hard code your key inside of your app code.

> Because we care, periodically the L.L. Bean API team will require 
credentials be regenerated. In the event this needs to occur the email 
address associated with your app will be notified.

To find the authorization credentials for an existing app, follow these steps:
1. Go to the Developer Channel http://developer.llbean.com
2. In the top right, hover over your email address and click my apps.
3. Select an application to view its authorization credentials.
4. Make your API request passing your consumer key

### 2. Transport Layer Security (TLS):
All API service endpoints are encrypted using SSL. Strict use of HTTPS avoids 
intercepting the API calls and authorization headers between your app and 
the L.L.Bean API platform.

### 3. Application Layer Validation
All developer apps must be approved by an L.L.Bean API administrator and 
provided a consumer key and secret. It is of utmost importance that you, 
the app developer, treat these credentials with special care.

## Traffic Management

The Events API uses a combination of low and high-traffic management 
policies to protect your app, and L.L.Bean's back, from excessive load. All 
API requests are subject to a default policy; however, as a customization, 
each individual developer app can have a value set by an API management team member.

### Spike Arrests
SpikeArrests stop traffic spikes (or bursts) that can be caused by an increase 
in usage, buggy clients, or malicious attacks.

| Policy   | Number of requests (default)  | Units
| :------  | :--------                     | :---- 
| High Use | 15                            | Per second
| Low Use  | 3                             | Per second

### Quota Management
A Quota is an allotment of request messages that an app is allowed to submit 
to an API over the course of an hour, a day, a week, or a month.

| Policy   | Number of requests (default)  | Units
| :------  | :--------                     | :---- 
| High Use | 500                           | Per hour or per Developer App
| Low Use  | 100                           | Per hour or per Developer App


> Okay now I'm ready for the really gory details. Let's see all those specs again in a detailed tabular format.
The following information has been designed to provide a detailed REST API specification for the Events API.

# Group ODS Events Resource
Group description (also with *Markdown*)

## Events Occurrence [/v1/events/{event_id}{?expand}]
Represents the event occurrence entity.

+ Parameters

   + event_id  (required, integer, `83670`) ...Event Ids can be found under Activities and are related to Departments e.g. Snowshoeing, Cross-Country Skiing, etc.
   + expand  (optional, string, `qualifiers`) ...Includes or excludes elements dynamically from payload.  Mutiple values can be added using commas.
 
        + Values
            + `qualifiers`
            + `skus`
            + `occurrences`
            + `spots`
            + `timeblocks`
            + `rsvtntyps`


+ Model

    + Headers

            X-LLBean-current_requests_used: 1
            X-LLBean-quota_expiration_time: 1395964800000
            X-LLBean-requests_left_in_quota: 999
            X-LLBean-spike_arrest_allowed_count: 10
            X-LLBean-spike_arrest_exceed_count: 0
            X-LLBean-spike_arrest_used_count: 1
            X-LLBean-total_requests_allowed_to_account: 1000

    + Body

            {
              "properties": {
                "name": "Monhegan Island Birding Hike",
                "imageData": {
                  "path": "//ecdiss.llbean.com/is/image/wim/",
                  "dimensions": {
                    "main": {
                      "width": "428",
                      "height": "494"
                    },
                    "thumbnail": {
                      "width": "58",
                      "height": "67"
                    }
                  },
                  "images": [
                    {
                      "id": "279472_0_41",
                      "defaultImage": true,
                      "imageText": "main",
                      "path": "//cdni.llbean.com/is/image/wim/279472_0_41"
                    },
                    {
                      "id": "279472_0_44",
                      "defaultImage": false,
                      "imageText": "Additional View 1",
                      "path": "//cdni.llbean.com/is/image/wim/279472_0_44"
                    }
                  ]
                },
                "seq": 0,
                "priceRange": "$149.00",
                "holdTimeLimit": 20,
                "childParticipantRequiresAdult": true,
                "waitListAvailable": true,
                "eventLocations": [
                  {
                    "id": 3,
                    "name": "Freeport Retail Store",
                    "city": "Freeport",
                    "state": "ME",
                    "zipCode": "04032",
                    "addressLine1": "95 Main St",
                    "addressLine2": "",
                    "isSelected": true,
                    "latitudeText": "43.857949",
                    "longitudeText": "-70.103322",
                    "selectedOccurrenceIndex": -1
                  }
                ],
                "metricPath": "Outdoor Discovery Schools:Bird Watching",
                "metricDeptName": "Outdoor Discovery Schools",
                "metricDeptId": 33,
                "metricSubDeptName": "Bird Watching",
                "metricSubDeptId": 513834,
                "metricSub2DeptId": 0,
                "metricSub3DeptId": 0,
                "categoryId": "83652",
                "catalogId": "TA",
                "displayId": "279472",
                "productId": "1365340"
              },
              "actions": {},
              "class": [
                "event"
              ],
              "links": [
                {
                  "rel": "self",
                  "href": "https://api.llbean.com/v1/events/83652"
                }
              ]
            }

            + Schema

            {
              "type": "object",
              "$schema": "http://json-schema.org/draft-03/schema",
              "id": "http://api.llbean.com",
              "required": false,
              "properties": {
                "actions": {
                  "type": "object",
                  "id": "http://api.llbean.com/actions",
                  "required": false
                },
                "class": {
                  "type": "array",
                  "id": "http://api.llbean.com/class",
                  "required": false,
                  "items": {
                    "type": "string",
                    "id": "http://api.llbean.com/class/0",
                    "required": false
                  }
                },
                "links": {
                  "type": "array",
                  "id": "http://api.llbean.com/links",
                  "required": false,
                  "items": {
                    "type": "object",
                    "id": "http://api.llbean.com/links/0",
                    "required": false,
                    "properties": {
                      "href": {
                        "type": "string",
                        "id": "http://api.llbean.com/links/0/href",
                        "required": false
                      },
                      "rel": {
                        "type": "string",
                        "id": "http://api.llbean.com/links/0/rel",
                        "required": false
                      }
                    }
                  }
                },
                "properties": {
                  "type": "object",
                  "id": "http://api.llbean.com/properties",
                  "required": false,
                  "properties": {
                    "catalogId": {
                      "type": "string",
                      "id": "http://api.llbean.com/properties/catalogId",
                      "required": false
                    },
                    "categoryId": {
                      "type": "string",
                      "id": "http://api.llbean.com/properties/categoryId",
                      "required": false
                    },
                    "childParticipantRequiresAdult": {
                      "type": "boolean",
                      "id": "http://api.llbean.com/properties/childParticipantRequiresAdult",
                      "required": false
                    },
                    "displayId": {
                      "type": "string",
                      "id": "http://api.llbean.com/properties/displayId",
                      "required": false
                    },
                    "eventLocations": {
                      "type": "array",
                      "id": "http://api.llbean.com/properties/eventLocations",
                      "required": false,
                      "items": {
                        "type": "object",
                        "id": "http://api.llbean.com/properties/eventLocations/0",
                        "required": false,
                        "properties": {
                          "addressLine1": {
                            "type": "string",
                            "id": "http://api.llbean.com/properties/eventLocations/0/addressLine1",
                            "required": false
                          },
                          "addressLine2": {
                            "type": "string",
                            "id": "http://api.llbean.com/properties/eventLocations/0/addressLine2",
                            "required": false
                          },
                          "city": {
                            "type": "string",
                            "id": "http://api.llbean.com/properties/eventLocations/0/city",
                            "required": false
                          },
                          "id": {
                            "type": "number",
                            "id": "http://api.llbean.com/properties/eventLocations/0/id",
                            "required": false
                          },
                          "isSelected": {
                            "type": "boolean",
                            "id": "http://api.llbean.com/properties/eventLocations/0/isSelected",
                            "required": false
                          },
                          "latitudeText": {
                            "type": "string",
                            "id": "http://api.llbean.com/properties/eventLocations/0/latitudeText",
                            "required": false
                          },
                          "longitudeText": {
                            "type": "string",
                            "id": "http://api.llbean.com/properties/eventLocations/0/longitudeText",
                            "required": false
                          },
                          "name": {
                            "type": "string",
                            "id": "http://api.llbean.com/properties/eventLocations/0/name",
                            "required": false
                          },
                          "selectedOccurrenceIndex": {
                            "type": "number",
                            "id": "http://api.llbean.com/properties/eventLocations/0/selectedOccurrenceIndex",
                            "required": false
                          },
                          "state": {
                            "type": "string",
                            "id": "http://api.llbean.com/properties/eventLocations/0/state",
                            "required": false
                          },
                          "zipCode": {
                            "type": "string",
                            "id": "http://api.llbean.com/properties/eventLocations/0/zipCode",
                            "required": false
                          }
                        }
                      }
                    },
                    "holdTimeLimit": {
                      "type": "number",
                      "id": "http://api.llbean.com/properties/holdTimeLimit",
                      "required": false
                    },
                    "imageData": {
                      "type": "object",
                      "id": "http://api.llbean.com/properties/imageData",
                      "required": false,
                      "properties": {
                        "dimensions": {
                          "type": "object",
                          "id": "http://api.llbean.com/properties/imageData/dimensions",
                          "required": false,
                          "properties": {
                            "main": {
                              "type": "object",
                              "id": "http://api.llbean.com/properties/imageData/dimensions/main",
                              "required": false,
                              "properties": {
                                "height": {
                                  "type": "string",
                                  "id": "http://api.llbean.com/properties/imageData/dimensions/main/height",
                                  "required": false
                                },
                                "width": {
                                  "type": "string",
                                  "id": "http://api.llbean.com/properties/imageData/dimensions/main/width",
                                  "required": false
                                }
                              }
                            },
                            "thumbnail": {
                              "type": "object",
                              "id": "http://api.llbean.com/properties/imageData/dimensions/thumbnail",
                              "required": false,
                              "properties": {
                                "height": {
                                  "type": "string",
                                  "id": "http://api.llbean.com/properties/imageData/dimensions/thumbnail/height",
                                  "required": false
                                },
                                "width": {
                                  "type": "string",
                                  "id": "http://api.llbean.com/properties/imageData/dimensions/thumbnail/width",
                                  "required": false
                                }
                              }
                            }
                          }
                        },
                        "images": {
                          "type": "array",
                          "id": "http://api.llbean.com/properties/imageData/images",
                          "required": false,
                          "items": {
                            "type": "object",
                            "id": "http://api.llbean.com/properties/imageData/images/0",
                            "required": false,
                            "properties": {
                              "defaultImage": {
                                "type": "boolean",
                                "id": "http://api.llbean.com/properties/imageData/images/0/defaultImage",
                                "required": false
                              },
                              "id": {
                                "type": "string",
                                "id": "http://api.llbean.com/properties/imageData/images/0/id",
                                "required": false
                              },
                              "imageText": {
                                "type": "string",
                                "id": "http://api.llbean.com/properties/imageData/images/0/imageText",
                                "required": false
                              },
                              "path": {
                                "type": "string",
                                "id": "http://api.llbean.com/properties/imageData/images/0/path",
                                "required": false
                              }
                            }
                          }
                        },
                        "path": {
                          "type": "string",
                          "id": "http://api.llbean.com/properties/imageData/path",
                          "required": false
                        }
                      }
                    },
                    "metricDeptId": {
                      "type": "number",
                      "id": "http://api.llbean.com/properties/metricDeptId",
                      "required": false
                    },
                    "metricDeptName": {
                      "type": "string",
                      "id": "http://api.llbean.com/properties/metricDeptName",
                      "required": false
                    },
                    "metricPath": {
                      "type": "string",
                      "id": "http://api.llbean.com/properties/metricPath",
                      "required": false
                    },
                    "metricSub2DeptId": {
                      "type": "number",
                      "id": "http://api.llbean.com/properties/metricSub2DeptId",
                      "required": false
                    },
                    "metricSub3DeptId": {
                      "type": "number",
                      "id": "http://api.llbean.com/properties/metricSub3DeptId",
                      "required": false
                    },
                    "metricSubDeptId": {
                      "type": "number",
                      "id": "http://api.llbean.com/properties/metricSubDeptId",
                      "required": false
                    },
                    "metricSubDeptName": {
                      "type": "string",
                      "id": "http://api.llbean.com/properties/metricSubDeptName",
                      "required": false
                    },
                    "name": {
                      "type": "string",
                      "id": "http://api.llbean.com/properties/name",
                      "required": false
                    },
                    "priceRange": {
                      "type": "string",
                      "id": "http://api.llbean.com/properties/priceRange",
                      "required": false
                    },
                    "productId": {
                      "type": "string",
                      "id": "http://api.llbean.com/properties/productId",
                      "required": false
                    },
                    "seq": {
                      "type": "number",
                      "id": "http://api.llbean.com/properties/seq",
                      "required": false
                    },
                    "waitListAvailable": {
                      "type": "boolean",
                      "id": "http://api.llbean.com/properties/waitListAvailable",
                      "required": false
                    }
                  }
                }
              }
            }



### Get ODS Event by Id [GET]
Get info about the event occurance.

+ Request

    + Headers

            key: fjduskenfhysnfksh773n63n==

+ Response 200 (application/json)
    
    [Events Occurrence][]

+ Response 404 (application/json)

    + Body

            {
              "fault": {
                "detail": {
                  "errorcode": "404",
                  "href": "https://developer.llbean.com/errors/LLB-O404",
                  "message": "Event ID not found"
                },
                "faultstring": "Event ID not found"
              }
            }


## Events Search [/v1/events/search{?locationid,eventtypeid,eventlevelid,pricerangeid,startdate,deptid,startIndex,expand}]
Represents the event occurrence search entity.

+ Parameters

    + locationid (optional, string, `574`) ... Filter the results by the given locations where the event is held
    + eventtypeid (optional, string, `2474,2441`) ...Filter the results by the given event type
    + eventlevelid (optional, string, `2475,2443`) ...Filter the results by the given event level 
    + pricerangeid (optional, string, `1,3`) ...Ids of price ranges to include.
    + startdate (optional, string, `2/26/2014`) ...Start date to look for event occurrences. Defaults to current date.
    + deptid (optional, string, `33`) ...The department id the event
    + startIndex (optional, integer, `33`) ...Start index relative to total elements (note total element)
    + expand  (optional, string, `refinements`) ...Includes or excludes elements dynamically from payload
 
        + Values
            + `refinements`

+ Model

    + Headers

            X-LLBean-current_requests_used: 1
            X-LLBean-quota_expiration_time: 1395964800000
            X-LLBean-requests_left_in_quota: 999
            X-LLBean-spike_arrest_allowed_count: 10
            X-LLBean-spike_arrest_exceed_count: 0
            X-LLBean-spike_arrest_used_count: 1
            X-LLBean-total_requests_allowed_to_account: 1000

    + Body

            {
              "properties": {
                "startIndex": 1,
                "endIndex": 50,
                "total": 158,
                "categoryId": "33",
                "filterData": "{\"STORE_CITY_STATE\":[\"524\"],\"EVENT_TYPE\":[\"0\"],\"EVENT_LEVEL\":[\"0\"],\"PRICE_RANGE\":[\"0\"],\"fromDate\":\"2/26/2014\",\"categoryId\":\"33\",\"isRetail\":false}",
                "dataLayerExecutionTime": 449,
                "actionTime": 66,
                "eventOccurrenceGroups": [
                  {
                    "monthYear": "February, 2014",
                    "isEventScheduled": true,
                    "eventOccurrences": [
                      {
                        "eventId": "83613",
                        "locationId": 524,
                        "timeBlocks": [
                          {
                            "start": "Feb 26, 2014 8:00:00 AM EST",
                            "end": "Feb 26, 2014 12:00:00 PM EST"
                          },
                          {
                            "start": "Feb 27, 2014 12:00:00 PM EST",
                            "end": "Feb 27, 2014 3:00:00 PM EST"
                          }
                        ],
                        "name": "Intermediate Shotgun Sports Course",
                        "location": "Freeport, ME",
                        "price": "$245",
                        "status": "This event occurs in the past",
                        "isMultiDay": true,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "https://dev.api.llbean.com/v1/events/83613"
                          }
                        ],
                        "occurrenceId": "4807",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83628",
                        "locationId": 3,
                        "timeBlocks": [
                          {
                            "start": "Feb 26, 2014 9:00:00 AM EST",
                            "end": "Feb 26, 2014 5:00:00 PM EST"
                          },
                          {
                            "start": "Mar 5, 2014 8:00:00 AM EST",
                            "end": "Mar 5, 2014 4:00:00 PM EST"
                          },
                          {
                            "start": "Mar 10, 2014 10:00:00 AM EDT",
                            "end": "Mar 10, 2014 10:00:00 AM EDT"
                          }
                        ],
                        "name": "Winter Sampler",
                        "location": "Freeport, ME",
                        "price": "$559 to $599",
                        "status": "This event occurs in the past",
                        "isMultiDay": true,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "https://dev.api.llbean.com/v1/events/83628"
                          }
                        ],
                        "occurrenceId": "4796",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83611",
                        "locationId": 515,
                        "timeBlocks": [
                          {
                            "start": "Feb 27, 2014 12:00:00 AM EST",
                            "end": "Feb 27, 2014 3:00:00 AM EST"
                          }
                        ],
                        "name": "Women's-Only Introduction to Shotgun Sports Course",
                        "location": "Freeport, ME",
                        "price": "$129",
                        "status": "Event Cancelled",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "https://dev.api.llbean.com/v1/events/83611"
                          }
                        ],
                        "occurrenceId": "4097",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83671",
                        "locationId": 515,
                        "timeBlocks": [
                          {
                            "start": "Feb 27, 2014 8:00:00 AM EST",
                            "end": "Feb 27, 2014 11:00:00 AM EST"
                          }
                        ],
                        "name": "Private Sporting-Clays Lesson",
                        "location": "Freeport, ME",
                        "price": "$165 to $248",
                        "status": "This event occurs in the past",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "https://dev.api.llbean.com/v1/events/83671"
                          }
                        ],
                        "occurrenceId": "4547",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 3,
                        "timeBlocks": [
                          {
                            "start": "Feb 28, 2014 6:00:00 PM EST",
                            "end": "Feb 28, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Freeport, ME",
                        "price": "$40",
                        "status": "This event occurs in the past",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "https://dev.api.llbean.com/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "2996",
                        "class": [
                          "event"
                        ]
                      }
                    ]
                  }
                ]
              },
              "class": [
                "eventOccurrences"
              ],
              "links": [
                {
                  "rel": "self",
                  "href": "/v1/events/search?locationid=524&eventtypeid=null&eventlevelid=null&pricerangeid=null&startdate=2/26/2014&deptid=33&startIndex=1"
                },
                {
                  "rel": "next",
                  "href": "https://dev.api.llbean.com/v1/events/search?startIndex=51&locationid=524&startdate=2/26/2014&deptid=33"
                }
              ]
            }

### Find Events Occurrences By Filter Criteria [GET]
Get info about the rain.
+ Request

    + Headers

            key: fjduskenfhysnfksh773n63n==

+ Response 200

    [Events Search][]

+ Response 404

    + Body

            {
              "fault": {
                "detail": {
                  "errorcode": "404",
                  "href": "https://developer.llbean.com/errors/LLB-404",
                  "message": "Event Occurrences not found.",
                  "details": {
                    "errorMessage": {
                      "PERS_FILTER_NO_SELECTION_AVAILABLE":"No scheduled events matching your search"
                    }
                  },
                  "faultstring": "Event Occurrences not found"
                }
              }
            }

+ Response 500

    + Body

            {
              "fault": {
                "detail": {
                  "errorcode": "500",
                  "href": "https://developer.llbean.com/errors/LLB-O400",
                  "message": "Event Occurrences not found.",
                  "details": {
                    "errorMessage": {
                      "PERS_NOT_AVAILABLE": "We're sorry, we are experiencing technical problems with our reservation system. Please try again later or call 1-888-270-2326 to complete your reservation."
                    }
                  },
                  "faultstring": "An exception happen during search"
                }
              }
            }

+ Response 400

    + Body

            {
              "fault": {
                "detail": {
                  "errorcode": "404",
                  "href": "https://developer.llbean.com/errors/LLB-404",
                  "message": "Invalid Pagination Parameters."
                },
                "faultstring": "Invalid Pagination Parameters"
              }
            }


