FORMAT: 1A
HOST: http://api.llbean.com

# ODS Event Search Resource

### API Status
|                      |               |
|  :------             |  :------      
| __Status__           | v1 Live  | 
| __Related Targets__  | LLBean Public Events Reservation System (PERS) | 
| __Description__      | ODS Events API | 
| __Product__          | Gateway | 
| __Known Issues__     | None | 
| __Monitoring__       | See LLBEAN ODS Events Monitoring | 
| __Key and Secret__   | Key Required | 


### Service Software Level Agreement (SLA)
| Max Response Time (Milliseconds)  | Estimated Max Requests Per Hour  |
|:-----  |:------ |
| 1,500  | 24,000 |

### Resources and URIs
####Request Headers
Media types accepted by consumer.
 
| Header   |  Description         |
| :------  | :------              |
| Accept   | application/json     |
| Key      | Developer App Key provided by Dev Portal. |

#### Response Headers
Response header for Southbound API will be honored and set to the response of Northbound API. See list of currently supported headers LLBean Notable Response Headers

| Name   |  Description   |  Example  |
| :------ | :------ | :------  |
| Content-Type | The MIME type of the body of the request. | application/json  |
| X-LLBean-Spike-Arrest-Allowed-Count | Allowed spike arrest count set by traffic management policies | 3 |
| X-LLBean-Quota-Allowed-Count | Allowed quota count set by traffic management policies | 300 |

### Traffic Management
All traffic to L.L.Bean Events by ID Resource is to be tracked by retrieving App Key from all requests made by all Consumer Apps.

#### Spike Arrest Management
SpikeArrests stop traffic spikes (or bursts) that can be caused by an increase in usage, buggy clients, or malicious attacks.

| Policy  | Number of request |  Units  |
| :------  | :------  | :------ |
| API Product Level (default) | 10 | Per second  |
| App Level | CUSTOM_VALUE (10) | Per second |

#### Quota Management
A Quota is an allotment of request messages that an app is allowed to submit to an API over the course of an hour, a day, a week, or a month.

| Policy  | Number of request  | Units  |
| :------ | :------- | :------ |
| Default | 10800 | Per hour |
| App Level | CUSTOM_VALUE (10800) | Per hour |

# Group Example Requests

## Outdoor Discovery School Event Search [/v1/events/search?locationid={locationid}&eventtypeid={eventtypeid}&eventlevelid={eventlevelid}&pricerangeid={pricerangeid}&startdate={startdate}&deptid={deptid}&startIndex={startIndex}&expand={expand}]
The following example eepresents the event occurrence search entity.

+ Parameters
    + locationid (optional, string, `123`) ... Filter the results by the given locations where the event is held
    + eventtypeid (optional, string, `2474,2441`) ... Filter the results by the given event type
    + eventlevelid (optional, string, `2475,2443`) ... Filter the results by the given event level
    + pricerangeid (optional, string, `1,3`) ... Ids of price ranges to include
    + startdate (optional, string, `2/26/2014`) ... Start date to look for event occurrences. Defaults to current date
    + deptid (optional, string, `33`) ... The department id the event
    + startIndex (optional, string, `1`) ... Start index relative to total elements
    + expand (optional, string, `refinements`) ... Includes elements dynamically from payload

### Event Search  [GET]
+ Response 200 (application/json)

    + Header

            Accept: application/json
            Key: Developer App Key provided by Dev Portal.

    + Body

             {
              "properties": {
                "startIndex": 1,
                "endIndex": 50,
                "total": 361,
                "categoryId": "33",
                "persRefinementsSelected": {
                  "STORE_CITY_STATE": [
                    "0"
                  ],
                  "EVENT_TYPE": [
                    "2438"
                  ],
                  "EVENT_LEVEL": [
                    "0"
                  ],
                  "PRICE_RANGE": [
                    "0"
                  ],
                  "fromDate": "2/13/2014",
                  "categoryId": "33",
                  "isRetail": false
                },
                "filterData": "{\"STORE_CITY_STATE\":[\"0\"],\"EVENT_TYPE\":[\"2438\"],\"EVENT_LEVEL\":[\"0\"],\"PRICE_RANGE\":[\"0\"],\"fromDate\":\"2/13/2014\",\"categoryId\":33,\"isRetail\":false}",
                "dataLayerExecutionTime": 377,
                "actionTime": 16,
                "refinements": [
                  {
                    "key": "STORE_CITY_STATE",
                    "value": "Events Near",
                    "id": 1,
                    "refinementValues": [
                      {
                        "key": "13",
                        "value": "Albany, NY ",
                        "isSelected": false
                      },
                      {
                        "key": "16",
                        "value": "Bangor, ME ",
                        "isSelected": false
                      },
                      {
                        "key": "11",
                        "value": "Burlington, MA ",
                        "isSelected": false
                      },
                      {
                        "key": "12",
                        "value": "Center Valley, PA ",
                        "isSelected": false
                      },
                      {
                        "key": "8",
                        "value": "Concord, NH ",
                        "isSelected": false
                      },
                      {
                        "key": "28",
                        "value": "Danbury, CT ",
                        "isSelected": false
                      },
                      {
                        "key": "19",
                        "value": "Dedham, MA ",
                        "isSelected": false
                      },
                      {
                        "key": "6",
                        "value": "Ellsworth, ME ",
                        "isSelected": false
                      },
                      {
                        "key": "29",
                        "value": "Fayetteville, NY ",
                        "isSelected": false
                      },
                      {
                        "key": "27",
                        "value": "Freehold, NJ ",
                        "isSelected": false
                      },
                      {
                        "key": "566",
                        "value": "Freeport, ME ",
                        "isSelected": false
                      },
                      {
                        "key": "25",
                        "value": "King Of Prussia, PA ",
                        "isSelected": false
                      },
                      {
                        "key": "30",
                        "value": "North Hampton, NH ",
                        "isSelected": false
                      },
                      {
                        "key": "10",
                        "value": "Manchester, NH ",
                        "isSelected": false
                      },
                      {
                        "key": "15",
                        "value": "Mansfield, MA ",
                        "isSelected": false
                      },
                      {
                        "key": "2",
                        "value": "Marlton, NJ ",
                        "isSelected": false
                      },
                      {
                        "key": "7",
                        "value": "Nashua, NH ",
                        "isSelected": false
                      },
                      {
                        "key": "5",
                        "value": "North Conway, NH ",
                        "isSelected": false
                      },
                      {
                        "key": "18",
                        "value": "Orange, CT ",
                        "isSelected": false
                      },
                      {
                        "key": "26",
                        "value": "Paramus, NJ ",
                        "isSelected": false
                      },
                      {
                        "key": "22",
                        "value": "Pittsburgh, PA ",
                        "isSelected": false
                      },
                      {
                        "key": "24",
                        "value": "Yonkers, NY ",
                        "isSelected": false
                      },
                      {
                        "key": "14",
                        "value": "South Windsor, CT ",
                        "isSelected": false
                      },
                      {
                        "key": "20",
                        "value": "Skokie, IL ",
                        "isSelected": false
                      },
                      {
                        "key": "21",
                        "value": "South Barrington, IL ",
                        "isSelected": false
                      },
                      {
                        "key": "1",
                        "value": "McLean, VA ",
                        "isSelected": false
                      },
                      {
                        "key": "23",
                        "value": "Victor, NY ",
                        "isSelected": false
                      },
                      {
                        "key": "17",
                        "value": "Wareham, MA ",
                        "isSelected": false
                      },
                      {
                        "key": "9",
                        "value": "West Lebanon, NH ",
                        "isSelected": false
                      }
                    ]
                  },
                  {
                    "key": "EVENT_TYPE",
                    "value": "Event Type",
                    "id": 2,
                    "refinementValues": [
                      {
                        "key": "2474",
                        "value": "Discovery Course",
                        "isSelected": false
                      },
                      {
                        "key": "2436",
                        "value": "Instructional Course",
                        "isSelected": false
                      },
                      {
                        "key": "2438",
                        "value": "Day Tour",
                        "isSelected": true
                      },
                      {
                        "key": "2437",
                        "value": "Overnight Trip",
                        "isSelected": false
                      },
                      {
                        "key": "2441",
                        "value": "Private Lesson",
                        "isSelected": false
                      },
                      {
                        "key": "2439",
                        "value": "Instructor Certification Course",
                        "isSelected": false
                      },
                      {
                        "key": "2440",
                        "value": "Women's-Only Adventure",
                        "isSelected": false
                      },
                      {
                        "key": "2600",
                        "value": "Youth Camps",
                        "isSelected": false
                      }
                    ]
                  },
                  {
                    "key": "EVENT_LEVEL",
                    "value": "Skill Level",
                    "id": 3,
                    "refinementValues": [
                      {
                        "key": "2475",
                        "value": "Beginner",
                        "isSelected": false
                      },
                      {
                        "key": "2074",
                        "value": "Intermediate",
                        "isSelected": false
                      },
                      {
                        "key": "2443",
                        "value": "Advanced",
                        "isSelected": false
                      }
                    ]
                  },
                  {
                    "key": "PRICE_RANGE",
                    "value": "Price",
                    "id": 4,
                    "refinementValues": [
                      {
                        "key": "1",
                        "value": "$0 to $30",
                        "isSelected": false
                      },
                      {
                        "key": "2",
                        "value": "$30 to $50",
                        "isSelected": false
                      },
                      {
                        "key": "3",
                        "value": "$50 to $100",
                        "isSelected": false
                      },
                      {
                        "key": "4",
                        "value": "$100+",
                        "isSelected": false
                      }
                    ]
                  }
                ],
                "eventOccurrenceGroups": [
                  {
                    "monthYear": "February, 2014",
                    "isEventScheduled": true,
                    "eventOccurrences": [
                      {
                        "eventId": "83684",
                        "locationId": 482,
                        "timeBlocks": [
                          {
                            "start": "Feb 14, 2014 6:00:00 PM EST",
                            "end": "Feb 14, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Albany, NY",
                        "price": "$40",
                        "status": "This event occurs in the past",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35421",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 491,
                        "timeBlocks": [
                          {
                            "start": "Feb 14, 2014 6:00:00 PM EST",
                            "end": "Feb 14, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Victor, NY",
                        "price": "$40",
                        "status": "This event occurs in the past",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35445",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 505,
                        "timeBlocks": [
                          {
                            "start": "Feb 14, 2014 6:00:00 PM EST",
                            "end": "Feb 14, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "South Barrington, IL",
                        "price": "$40",
                        "status": "This event occurs in the past",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35437",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 510,
                        "timeBlocks": [
                          {
                            "start": "Feb 14, 2014 6:00:00 PM EST",
                            "end": "Feb 14, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Enfield, NH",
                        "price": "$40",
                        "status": "This event occurs in the past",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35466",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 515,
                        "timeBlocks": [
                          {
                            "start": "Feb 14, 2014 6:00:00 PM EST",
                            "end": "Feb 14, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Freeport, ME",
                        "price": "$40",
                        "status": "This event occurs in the past",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35410",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 562,
                        "timeBlocks": [
                          {
                            "start": "Feb 14, 2014 6:00:00 PM EST",
                            "end": "Feb 14, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Cazenovia, NY",
                        "price": "$40",
                        "status": "This event occurs in the past",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35457",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 564,
                        "timeBlocks": [
                          {
                            "start": "Feb 14, 2014 6:00:00 PM EST",
                            "end": "Feb 14, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Allison Park, PA",
                        "price": "$40",
                        "status": "This event occurs in the past",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35429",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 482,
                        "timeBlocks": [
                          {
                            "start": "Feb 21, 2014 6:00:00 PM EST",
                            "end": "Feb 21, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Albany, NY",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35422",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 491,
                        "timeBlocks": [
                          {
                            "start": "Feb 21, 2014 6:00:00 PM EST",
                            "end": "Feb 21, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Victor, NY",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35446",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 505,
                        "timeBlocks": [
                          {
                            "start": "Feb 21, 2014 6:00:00 PM EST",
                            "end": "Feb 21, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "South Barrington, IL",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35438",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 510,
                        "timeBlocks": [
                          {
                            "start": "Feb 21, 2014 6:00:00 PM EST",
                            "end": "Feb 21, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Enfield, NH",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35467",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 515,
                        "timeBlocks": [
                          {
                            "start": "Feb 21, 2014 6:00:00 PM EST",
                            "end": "Feb 21, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Freeport, ME",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35411",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 562,
                        "timeBlocks": [
                          {
                            "start": "Feb 21, 2014 6:00:00 PM EST",
                            "end": "Feb 21, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Cazenovia, NY",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35455",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 564,
                        "timeBlocks": [
                          {
                            "start": "Feb 21, 2014 6:00:00 PM EST",
                            "end": "Feb 21, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Allison Park, PA",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35430",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83591",
                        "locationId": 550,
                        "timeBlocks": [
                          {
                            "start": "Feb 22, 2014 10:00:00 AM EST",
                            "end": "Feb 22, 2014 3:00:00 PM EST"
                          }
                        ],
                        "name": "Pleasant Mountain Guided Snowshoe Hike",
                        "location": "Bridgton, ME",
                        "price": "$79",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83591"
                          }
                        ],
                        "occurrenceId": "35527",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 482,
                        "timeBlocks": [
                          {
                            "start": "Feb 28, 2014 6:00:00 PM EST",
                            "end": "Feb 28, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Albany, NY",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35423",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 491,
                        "timeBlocks": [
                          {
                            "start": "Feb 28, 2014 6:00:00 PM EST",
                            "end": "Feb 28, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Victor, NY",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35447",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 505,
                        "timeBlocks": [
                          {
                            "start": "Feb 28, 2014 6:00:00 PM EST",
                            "end": "Feb 28, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "South Barrington, IL",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35439",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 510,
                        "timeBlocks": [
                          {
                            "start": "Feb 28, 2014 6:00:00 PM EST",
                            "end": "Feb 28, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Enfield, NH",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35468",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 515,
                        "timeBlocks": [
                          {
                            "start": "Feb 28, 2014 6:00:00 PM EST",
                            "end": "Feb 28, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Freeport, ME",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35412",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 562,
                        "timeBlocks": [
                          {
                            "start": "Feb 28, 2014 6:00:00 PM EST",
                            "end": "Feb 28, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Cazenovia, NY",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35456",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83684",
                        "locationId": 564,
                        "timeBlocks": [
                          {
                            "start": "Feb 28, 2014 6:00:00 PM EST",
                            "end": "Feb 28, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Allison Park, PA",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35431",
                        "class": [
                          "event"
                        ]
                      }
                    ]
                  },
                  {
                    "monthYear": "March, 2014",
                    "isEventScheduled": true,
                    "eventOccurrences": [
                      {
                        "eventId": "83684",
                        "locationId": 515,
                        "timeBlocks": [
                          {
                            "start": "Mar 7, 2014 6:00:00 PM EST",
                            "end": "Mar 7, 2014 9:00:00 PM EST"
                          }
                        ],
                        "name": "Starlight Snowshoe Tour",
                        "location": "Freeport, ME",
                        "price": "$40",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83684"
                          }
                        ],
                        "occurrenceId": "35413",
                        "class": [
                          "event"
                        ]
                      }
                    ]
                  },
                  {
                    "monthYear": "May, 2014",
                    "isEventScheduled": true,
                    "eventOccurrences": [
                      {
                        "eventId": "83652",
                        "locationId": 547,
                        "timeBlocks": [
                          {
                            "start": "May 18, 2014 8:00:00 AM EDT",
                            "end": "May 18, 2014 4:30:00 PM EDT"
                          }
                        ],
                        "name": "Monhegan Island Birding Hike",
                        "location": "New Harbor, ME",
                        "price": "$149",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83652"
                          }
                        ],
                        "occurrenceId": "36600",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83637",
                        "locationId": 506,
                        "timeBlocks": [
                          {
                            "start": "May 23, 2014 5:30:00 PM EDT",
                            "end": "May 23, 2014 8:30:00 PM EDT"
                          }
                        ],
                        "name": "Sunset Kayak Tour",
                        "location": "Marlborough, CT",
                        "price": "$49",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83637"
                          }
                        ],
                        "occurrenceId": "36064",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "May 24, 2014 7:00:00 AM EDT",
                            "end": "May 24, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36702",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "May 25, 2014 7:00:00 AM EDT",
                            "end": "May 25, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36703",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "May 26, 2014 7:00:00 AM EDT",
                            "end": "May 26, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36704",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "May 27, 2014 7:00:00 AM EDT",
                            "end": "May 27, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36705",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "May 28, 2014 7:00:00 AM EDT",
                            "end": "May 28, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36706",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "May 29, 2014 7:00:00 AM EDT",
                            "end": "May 29, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36707",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "May 30, 2014 7:00:00 AM EDT",
                            "end": "May 30, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36708",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "May 31, 2014 7:00:00 AM EDT",
                            "end": "May 31, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36709",
                        "class": [
                          "event"
                        ]
                      }
                    ]
                  },
                  {
                    "monthYear": "June, 2014",
                    "isEventScheduled": true,
                    "eventOccurrences": [
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 1, 2014 7:00:00 AM EDT",
                            "end": "Jun 1, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36710",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 2, 2014 7:00:00 AM EDT",
                            "end": "Jun 2, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36711",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 3, 2014 7:00:00 AM EDT",
                            "end": "Jun 3, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36712",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 4, 2014 7:00:00 AM EDT",
                            "end": "Jun 4, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36713",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 5, 2014 7:00:00 AM EDT",
                            "end": "Jun 5, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36714",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 6, 2014 7:00:00 AM EDT",
                            "end": "Jun 6, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36715",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 7, 2014 7:00:00 AM EDT",
                            "end": "Jun 7, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36716",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83642",
                        "locationId": 526,
                        "timeBlocks": [
                          {
                            "start": "Jun 7, 2014 9:00:00 AM EDT",
                            "end": "Jun 7, 2014 1:00:00 PM EDT"
                          }
                        ],
                        "name": "Maine Guided Wildlife Tour, Tandem Kayak",
                        "location": "Freeport, ME",
                        "price": "$69",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83642"
                          }
                        ],
                        "occurrenceId": "36633",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 8, 2014 7:00:00 AM EDT",
                            "end": "Jun 8, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36717",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83642",
                        "locationId": 526,
                        "timeBlocks": [
                          {
                            "start": "Jun 8, 2014 9:00:00 AM EDT",
                            "end": "Jun 8, 2014 1:00:00 PM EDT"
                          }
                        ],
                        "name": "Maine Guided Wildlife Tour, Tandem Kayak",
                        "location": "Freeport, ME",
                        "price": "$69",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83642"
                          }
                        ],
                        "occurrenceId": "36634",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 9, 2014 7:00:00 AM EDT",
                            "end": "Jun 9, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36718",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 10, 2014 7:00:00 AM EDT",
                            "end": "Jun 10, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36719",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 11, 2014 7:00:00 AM EDT",
                            "end": "Jun 11, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36720",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83656",
                        "locationId": 513,
                        "timeBlocks": [
                          {
                            "start": "Jun 12, 2014 7:00:00 AM EDT",
                            "end": "Jun 12, 2014 3:00:00 PM EDT"
                          }
                        ],
                        "name": "Androscoggin River Fishing Trip",
                        "location": "Lisbon Falls, ME",
                        "price": "$595",
                        "status": "1 spot remaining",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83656"
                          }
                        ],
                        "occurrenceId": "36721",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83634",
                        "locationId": 12,
                        "timeBlocks": [
                          {
                            "start": "Jun 12, 2014 7:00:00 PM EDT",
                            "end": "Jun 12, 2014 10:00:00 PM EDT"
                          }
                        ],
                        "name": "Full-Moon Kayak Tour",
                        "location": "Center Valley, PA",
                        "price": "$49",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83634"
                          }
                        ],
                        "occurrenceId": "35910",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83634",
                        "locationId": 481,
                        "timeBlocks": [
                          {
                            "start": "Jun 12, 2014 7:00:00 PM EDT",
                            "end": "Jun 12, 2014 10:00:00 PM EDT"
                          }
                        ],
                        "name": "Full-Moon Kayak Tour",
                        "location": "Albany, NY",
                        "price": "$49",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83634"
                          }
                        ],
                        "occurrenceId": "35892",
                        "class": [
                          "event"
                        ]
                      },
                      {
                        "eventId": "83634",
                        "locationId": 487,
                        "timeBlocks": [
                          {
                            "start": "Jun 12, 2014 7:00:00 PM EDT",
                            "end": "Jun 12, 2014 10:00:00 PM EDT"
                          }
                        ],
                        "name": "Full-Moon Kayak Tour",
                        "location": "Danbury, CT",
                        "price": "$49",
                        "status": "Open",
                        "isMultiDay": false,
                        "isViewTimes": false,
                        "sameDayEventOccurrences": [],
                        "links": [
                          {
                            "rel": "self",
                            "href": "/v1/events/83634"
                          }
                        ],
                        "occurrenceId": "35929",
                        "class": [
                          "event"
                        ]
                      }
                    ]
                  }
                ]
              },
              "class": [
                "eventOccurrences"
              ],
              "links": [
                {
                  "rel": "self",
                  "href": "/v1/events/search?_TODO_REQUIRES_PARSING_DATA_FROM_REQUEST_PARAMETERS_TO_MEET_EVENT_OCCURRENCES_URL_SPEC e.g. /v1/events/search?locationid={locationid}&eventtypeid={eventtypeid}&eventlevelid={eventlevelid}&pricerangeid={pricerangeid}&startdate={startdate}&deptid={deptid}"
                },
                {
                  "rel": "next",
                  "href": "/v1/events/search?_TODO_NEXT_BATCH_OF_ELEMENTS_START_END_INDEX_SEE_showMoreURL e.g. /v1/events/search?locationid={locationid}&eventtypeid={eventtypeid}&eventlevelid={eventlevelid}&pricerangeid={pricerangeid}&startdate={startdate}&deptid={deptid}"
                }
              ]
            }

## Event Occurrences not found [/v1/events/search?locationid=123]
The following example represents the event occurrence search at a location where no events are currently being held.

+ Parameters
    + locationid (string, `123`) ... The invalid location id

### 404 - Event Occurrences not found [GET]
+ Response 404 (application/json)

    + Header

            Accept: application/json
            Key: Developer App Key provided by Dev Portal.

    + Body

            {
              "fault": {
                "detail": {
                  "errorcode": "404",
                  "href": "https://developer.llbean.com/errors/LLB-404",
                  "message": "Event Occurrences not found.",
                  "details": {
                    "errorMessage": {
                      "PERS_FILTER_NO_SELECTION_AVAILABLE":"No scheduled events matching your search"
                    }
                  },
                  "faultstring": "Event Occurrences not found"
                }
              }
            }

